### ISSUE TITLE
Keep a changelog file

### ISSUE THREAD

**Issue by Cleidiano** [GuiaBolso/events-protocol#47]
I'm create this issue to discuss if make sence for this project to include a CHANGELOG file as proposed by [https://keepachangelog.com/en/1.0.0/](https://keepachangelog.com/en/1.0.0/), I'am think so.

**Comment by Cleidiano** [comment]
@bruno-ortiz @josealmada

**Comment by Kerooker** [comment]
Perhaps closing this is a good option now that we have the `release-drafter` action, which updates the release-draft changelog whenever a pull request is merged into master. [2.10.0 was release this way ](https://github.com/GuiaBolso/events-protocol/releases/tag/2.10.0)

**Comment by Cleidiano** [comment]
Agreed.
