### ISSUE TITLE
[FIX] - Um regex extenso pode derrubar um contêiner/instancia.

### ISSUE THREAD

**Issue by srburton** [GuiaBolso/events-protocol#49]
Meu issue é sobre um Regex que possivelmente pode ser explorado para que o container/instancia possa ser derrubado ou com lentidão absurda. 

**Segue abaixo o Regex atual.** 

![Screenshot_7](https://user-images.githubusercontent.com/15394508/78709288-c8cfdc00-78e9-11ea-824e-9741023e8108.png)

**Regex proposto**

![Screenshot_10](https://user-images.githubusercontent.com/15394508/78712172-94aaea00-78ee-11ea-8390-ba70ffe156bc.png)

-  A validação de quantidade de carácter deve ser verificada antes de ser processada pelo Regex
exemplo de um site que tem um limite de carácter: 

![Screenshot_8](https://user-images.githubusercontent.com/15394508/78712421-f23f3680-78ee-11ea-8ec1-05a19f503ec0.png)

- A validação de quantidade de "blocos" deve ser feita via linguagem de programação.

**Comment by bruno-ortiz** [comment]
@srburton obrigado por abrir a issue. 
Acredito que hoje não é feita validação dessa Regex, e ela esta na DOC apenas como forma de ilustrar o formato do nome do evento.
Hoje utilizamos isso apenas como uma convenção e não como uma regra aplicada.
