### ISSUE TITLE
Support for Serialization/Deserialization of Kotlin Data Classes

### ISSUE THREAD

**Issue by diogoasouza** [GuiaBolso/events-protocol#62]
As of today, this lib utilizes GSON for serialization and deserialization of Jsons, but it doesn't provide support for kotlin's data classes, so default or nullable values don't work well

Suggestion: Have a module that utilizes a lib that supports kotlin, such as [Jackson](https://github.com/FasterXML/jackson-module-kotlin) or [Moshi](https://github.com/square/moshi/)

**Comment by Cleidiano** [comment]
I will give a try to implement this support
